apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi-server
    spec:
      containers:
      - image: gcr.io/$GCP_PROJECT_ID/$IMAGE_TAG
        name: fastapi-k8s
        ports:
        - containerPort: 80          
        resources: {}