apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: fastapi-server
  type: LoadBalancer
status:
  loadBalancer: {}